import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Container } from '@material-ui/core';

import { Provider } from 'react-redux';
import store from '../redux/store';

import TomeiStepper from '../components/TomeiStepper';
import TomeiForm from '../components/TomeiForm';

const Home = () => {

  return (
    <Provider store={store}>
      <div>
        <Head>
          <title>Tomei</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
          />
          <script
            defer
            src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"
          ></script>
        </Head>

        <main className={styles.main}>
          <Image src="/Logo.png" alt="Tomei Logo" width={210} height={60} />

          <div className={styles.stepper}>
            <TomeiStepper />
          </div>
        </main>
      </div>
    </Provider>
  );
}

export default Home;
