import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import TomeiStepper from '../components/TomeiStepper';
import TomeiForm from '../components/TomeiForm';
import { Container } from '@material-ui/core';
export default function Home() {
  return (
    <div  >
      <Head>
        <title>Tomei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css" />
        <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
      </Head>

      <main className={styles.main}>
        <Image src="/Logo.png" alt="Tomei Logo" width={210} height={60} />       

        <div className={styles.stepper}>
          <TomeiStepper />
        </div>

        <Container maxWidth="md">
          <TomeiForm title="Create Your Account"
            message="Because there will be documents that you need to prepare to apply for the loan, let's start
                    off by creating a password so that you can login to your account once you have these documents ready."/>
        </Container>
          
        
        
      </main>

    </div>
  )
}
