
export const GET_USER_ACCOUNTS = 'GET_USER_ACCOUNTS';
export const GET_USER_ACCOUNT = 'GET_USER_ACCOUNT';
export const ADD_USER_ACCOUNT = 'ADD_USER_ACCOUNT';
export const UPDATE_USER_ACCOUNT = 'UPDATE_USER_ACCOUNT';
export const DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT';
export const USER_ACCOUNT_ERROR = 'USER_ACCOUNT_ERROR';
export const USER_ACCOUNT_LOADING = 'USER_ACCOUNT_LOADING';
